"""
This module patches deep-translator to support all 245+ Google Translate languages.
"""
from deep_translator import constants

# The complete list of Google Translate supported languages (as of late 2024)
# Format: 'language name': 'code'
FULL_GOOGLE_LANGUAGES = {
    'abkhaz': 'ab',
    'acehnese': 'ace',
    'acholi': 'ach',
    'afar': 'aa',
    'afrikaans': 'af',
    'akan': 'ak',
    'albanian': 'sq',
    'alur': 'alz',
    'amharic': 'am',
    'arabic': 'ar',
    'armenian': 'hy',
    'assamese': 'as',
    'avar': 'av',
    'awadhi': 'awa',
    'aymara': 'ay',
    'azerbaijani': 'az',
    'balinese': 'ban',
    'baluchi': 'bal',
    'bambara': 'bm',
    'baoule': 'bci',
    'bashkir': 'ba',
    'basque': 'eu',
    'batak karo': 'btx',
    'batak simalungun': 'bts',
    'batak toba': 'bbc',
    'belarusian': 'be',
    'bemba': 'bem',
    'bengali': 'bn',
    'betawi': 'bew',
    'bhojpuri': 'bho',
    'bikol': 'bik',
    'bosnian': 'bs',
    'breton': 'br',
    'bulgarian': 'bg',
    'buryat': 'bua',
    'cantonese': 'yue',
    'catalan': 'ca',
    'cebuano': 'ceb',
    'chamorro': 'ch',
    'chechen': 'ce',
    'chichewa': 'ny',
    'chinese (simplified)': 'zh-CN',
    'chinese (traditional)': 'zh-TW',
    'chukchi': 'ckt',
    'chuvash': 'cv',
    'corsican': 'co',
    'crimean tatar': 'crh',
    'croatian': 'hr',
    'czech': 'cs',
    'danish': 'da',
    'dari': 'fa-AF',
    'dhivehi': 'dv',
    'dinka': 'din',
    'dogri': 'doi',
    'dombe': 'doh',
    'dutch': 'nl',
    'dyula': 'dyu',
    'dzongkha': 'dz',
    'english': 'en',
    'esperanto': 'eo',
    'estonian': 'et',
    'ewe': 'ee',
    'faroese': 'fo',
    'fijian': 'fj',
    'filipino': 'tl',
    'finnish': 'fi',
    'fon': 'fon',
    'french': 'fr',
    'frisian': 'fy',
    'friulian': 'fur',
    'fulani': 'ff',
    'ga': 'gaa',
    'galician': 'gl',
    'ganda': 'lg',
    'georgian': 'ka',
    'german': 'de',
    'goan konkani': 'gom',
    'greek': 'el',
    'guarani': 'gn',
    'gujarati': 'gu',
    'haitian creole': 'ht',
    'hakha chin': 'cnh',
    'hausa': 'ha',
    'hawaiian': 'haw',
    'hebrew': 'iw',
    'hiligaynon': 'hil',
    'hindi': 'hi',
    'hmong': 'hmn',
    'hungarian': 'hu',
    'hunsrik': 'hrx',
    'iban': 'iba',
    'icelandic': 'is',
    'igbo': 'ig',
    'ilocano': 'ilo',
    'indonesian': 'id',
    'inuktitut': 'iu',
    'inuktitut (latin)': 'ikt',
    'irish': 'ga',
    'italian': 'it',
    'jamaican patois': 'jam',
    'japanese': 'ja',
    'javanese': 'jw',
    'jingpo': 'kac',
    'kalaallisut': 'kl',
    'kannada': 'kn',
    'kanuri': 'kr',
    'kapampangan': 'pam',
    'kazakh': 'kk',
    'khasi': 'kha',
    'khmer': 'km',
    'kiga': 'cgg',
    'kikongo': 'kg',
    'kinyarwanda': 'rw',
    'kituba': 'ktu',
    'kokborok': 'trp',
    'komi': 'kv',
    'konkani': 'gom',
    'korean': 'ko',
    'krio': 'kri',
    'kurdish (kurmanji)': 'ku',
    'kurdish (sorani)': 'ckb',
    'kyrgyz': 'ky',
    'lao': 'lo',
    'latgalian': 'ltg',
    'latin': 'la',
    'latvian': 'lv',
    'ligurian': 'lij',
    'limbu': 'lif',
    'lingala': 'ln',
    'lithuanian': 'lt',
    'lombard': 'lmo',
    'luganda': 'lg',
    'luo': 'luo',
    'luxembourgish': 'lb',
    'macedonian': 'mk',
    'madurese': 'mad',
    'maithili': 'mai',
    'makassar': 'mak',
    'malagasy': 'mg',
    'malay': 'ms',
    'malay (jawi)': 'ms-Arab',
    'malayalam': 'ml',
    'maltese': 'mt',
    'mam': 'mam',
    'manx': 'gv',
    'maori': 'mi',
    'marathi': 'mr',
    'marshallese': 'mh',
    'marwadi': 'mwr',
    'mauritian creole': 'mfe',
    'meiteilon (manipuri)': 'mni-Mtei',
    'minang': 'min',
    'mizo': 'lus',
    'mongolian': 'mn',
    'myanmar': 'my',
    'nahuatl (eastern huasteca)': 'nhe',
    'ndau': 'ndc',
    'ndebele (south)': 'nr',
    'nepali': 'ne',
    'newari': 'new',
    'nko': 'nqo',
    'norwegian': 'no',
    'nuer': 'nus',
    'occitan': 'oc',
    'odia (oriya)': 'or',
    'oromo': 'om',
    'ossetian': 'os',
    'pangasinan': 'pag',
    'papiamento': 'pap',
    'pashto': 'ps',
    'persian': 'fa',
    'polish': 'pl',
    'portuguese': 'pt',
    'portuguese (portugal)': 'pt-PT',
    'portuguese (brazil)': 'pt-BR',
    'punjabi': 'pa',
    'punjabi (shahmukhi)': 'pa-Arab',
    'quechua': 'qu',
    'q\'eqchi\'': 'kek',
    'romani': 'rom',
    'romanian': 'ro',
    'rundi': 'rn',
    'russian': 'ru',
    'sami (north)': 'se',
    'samoan': 'sm',
    'sango': 'sg',
    'sanskrit': 'sa',
    'santali': 'sat',
    'scots gaelic': 'gd',
    'sepedi': 'nso',
    'serbian': 'sr',
    'sesotho': 'st',
    'shan': 'shn',
    'shona': 'sn',
    'sicilian': 'scn',
    'silesian': 'szl',
    'sindhi': 'sd',
    'sinhala': 'si',
    'slovak': 'sk',
    'slovenian': 'sl',
    'somali': 'so',
    'spanish': 'es',
    'sundanese': 'su',
    'sususu': 'sus',
    'swahili': 'sw',
    'swati': 'ss',
    'swedish': 'sv',
    'tahitian': 'ty',
    'tajik': 'tg',
    'tamazight': 'tzm',
    'tamazight (tifinagh)': 'zgh',
    'tamil': 'ta',
    'tatar': 'tt',
    'telugu': 'te',
    'tetum': 'tet',
    'thai': 'th',
    'tibetan': 'bo',
    'tigre': 'tig',
    'tigrinya': 'ti',
    'tiv': 'tiv',
    'tok pisin': 'tpi',
    'tonga': 'to',
    'tsonga': 'ts',
    'tswana': 'tn',
    'tulu': 'tcy',
    'tumbuha': 'tum',
    'turkish': 'tr',
    'turkmen': 'tk',
    'tuvinian': 'tyv',
    'twi': 'ak',
    'udmurt': 'udm',
    'ukrainian': 'uk',
    'urdu': 'ur',
    'uyghur': 'ug',
    'uzbek': 'uz',
    'venda': 've',
    'venetian': 'vec',
    'vietnamese': 'vi',
    'waray': 'war',
    'welsh': 'cy',
    'wolof': 'wo',
    'xhosa': 'xh',
    'yakut': 'sah',
    'yiddish': 'yi',
    'yoruba': 'yo',
    'yucatec maya': 'yua',
    'zapotec': 'zap',
    'zulu': 'zu'
}

def patch_deep_translator():
    """
    Updates the deep_translator constants to include the full list of languages.
    """
    # Update the internal dictionary
    constants.GOOGLE_LANGUAGES_TO_CODES.update(FULL_GOOGLE_LANGUAGES)
    
    # Also update the reverse mapping if it exists (it's usually computed dynamically, but just in case)
    # deep-translator uses GOOGLE_LANGUAGES_TO_CODES for validation.
    
    print(f"Patched deep-translator with {len(FULL_GOOGLE_LANGUAGES)} languages.")

if __name__ == "__main__":
    patch_deep_translator()
